version: '3.8'

services:
  # --- 1. AUTENTICACIÓN Y SEGURIDAD ---
  autenticacion-seguridad-service:
    image: 433634597248.dkr.ecr.us-east-1.amazonaws.com/iamfit/autenticacion-seguridad:latest
    container_name: autenticacion-seguridad-app
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iamfit-db-instance-1.ch37wpohshat.us-east-1.rds.amazonaws.com:5432/iamfit_db
      - SPRING_DATASOURCE_USERNAME=iamfit_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=master.iamfit-redis.wetuo3.use1.cache.amazonaws.com
      - RSA_PRIVATE=${RSA_PRIVATE}
      - RSA_PUBLIC=${RSA_PUBLIC}
    depends_on:
      - rabbitmq
    restart: unless-stopped

  # --- 2. USUARIOS Y PERFILES ---
  usuarios-perfiles-service:
    image: 433634597248.dkr.ecr.us-east-1.amazonaws.com/iamfit/usuarios-perfiles:latest
    container_name: usuarios-perfiles-app
    ports:
      - "8081:8080"
      - "50052:50051"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iamfit-db-instance-1.ch37wpohshat.us-east-1.rds.amazonaws.com:5432/iamfit_db
      - SPRING_DATASOURCE_USERNAME=iamfit_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=master.iamfit-redis.wetuo3.use1.cache.amazonaws.com
      - RSA_PUBLIC=${RSA_PUBLIC}
    depends_on:
      - rabbitmq
    restart: unless-stopped

  # --- 3. AI SERVICE ---
  ai-service:
    image: 433634597248.dkr.ecr.us-east-1.amazonaws.com/iamfit/ai-service:latest
    container_name: ai-service-app
    ports:
      - "8082:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iamfit-db-instance-1.ch37wpohshat.us-east-1.rds.amazonaws.com:5432/iamfit_db
      - SPRING_DATASOURCE_USERNAME=iamfit_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - RSA_PUBLIC=${RSA_PUBLIC}
      - GRPC_USUARIOS_HOST=usuarios-perfiles-app
      - GRPC_USUARIOS_PORT=50051
      - KEYSTORE_PASSWORD=iamfit2026
    depends_on:
      - rabbitmq
      - usuarios-perfiles-service
    restart: unless-stopped

  # --- 4. ALIMENTACIÓN ---
  alimentacion-service:
    image: 433634597248.dkr.ecr.us-east-1.amazonaws.com/iamfit/alimentacion:latest
    container_name: alimentacion-app
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iamfit-db-instance-1.ch37wpohshat.us-east-1.rds.amazonaws.com:5432/iamfit_db
      - SPRING_DATASOURCE_USERNAME=iamfit_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - RSA_PUBLIC=${RSA_PUBLIC}
      - CALORIENINJAS_API_KEY=${CALORIENINJAS_API_KEY}
    depends_on:
      - rabbitmq
      - usuarios-perfiles-service
    restart: unless-stopped

  # --- 5. EJERCICIOS ---
  ejercicios-service:
    image: 433634597248.dkr.ecr.us-east-1.amazonaws.com/iamfit/ejercicios:latest
    container_name: ejercicios-app
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iamfit-db-instance-1.ch37wpohshat.us-east-1.rds.amazonaws.com:5432/iamfit_db
      - SPRING_DATASOURCE_USERNAME=iamfit_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - RSA_PUBLIC=${RSA_PUBLIC}
    depends_on:
      - rabbitmq
      - usuarios-perfiles-service
    restart: unless-stopped

  # --- RABBITMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: iamfit-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

volumes: {}