spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/salud_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ai:
    google:
      genai:
        project-id: "gen-lang-client-0705803122"
        api-key: ${GOOGLE_API_KEY}
        location: us-central1
        chat:
          options:
            model: gemini-2.5-flash
            safety-settings:
              - category: HARM_CATEGORY_HARASSMENT
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_HATE_SPEECH
                threshold: BLOCK_NONE

        embedding:
          project-id: "gen-lang-client-0705803122"
          api-key: ${GOOGLE_API_KEY}
          options:
            model: text-embedding-004

    vectorstore:
      pgvector:
        initialize-schema: false
        table-name: vector_store
        dimensions: 768
        distance-type: COSINE_DISTANCE