server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{userIp}] %-5level %logger{36} - %msg%n"

spring:
  grpc:
    server:
      port: 9090
      http2:
        enabled: true


  application:
    name: usuarios-perfiles
