server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379

# CONFIGURACIÓN DEL CLIENTE gRPC
grpc:
  client:
    usuarios-perfiles-service:
      address: 'static://usuarios-perfiles-app:50051'
      negotiation-type: plaintext

RSA_PRIVATE: ${RSA_PRIVATE}
RSA_PUBLIC: ${RSA_PUBLIC}

app:
  cleanup:
    session:
      cron: "0 0 * * * ?"
    account:
      cron: "0 0 3 * * ?"
      grace-period-days: 30